### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by liu52020** [ThomasWestfechtel/StairwayDetection#3]
Why can't I get results when using your program and .pcd data?
![image](https://user-images.githubusercontent.com/73093990/126892806-69d7b256-df41-4f81-8c34-107f7b803628.png)

**Comment by ThomasWestfechtel** [comment]
Should be fixed

**Comment by shaheer34mts** [comment]
Hi @ThomasWestfechtel , In the example "25_Depth.pcd", it prints that it has 69 treads and 57 risers. But I can only see 5 treads (blue) and 5 risers (red). Can you please explain why it prints so many number of treads and risers ?

![Screenshot from 2023-05-18 12-46-40](https://github.com/ThomasWestfechtel/StairwayDetection/assets/32576477/fcaa5ad0-065d-456c-ae41-4f25891f40ca)
![Screenshot from 2023-05-18 12-49-12](https://github.com/ThomasWestfechtel/StairwayDetection/assets/32576477/5dc3293a-ae7e-47fb-b35d-66def3a2595b)
